  
name: rl-project
channels:
    - conda-forge
    - pytorch
dependencies:
    - python==3.6.9
    - numpy==1.17.2
    - pip
    - pip:
        - scipy
        - tqdm
        - wheel
        - matplotlib==3.2.1
        - keras
        - tensorflow==2.3.0
        - nltk==3.2.5
        - transformers
        - torch
        - torchvision
